// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	focusFieldNames          = builder.RawFieldNames(&Focus{})
	focusRows                = strings.Join(focusFieldNames, ",")
	focusRowsExpectAutoSet   = strings.Join(stringx.Remove(focusFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	focusRowsWithPlaceHolder = strings.Join(stringx.Remove(focusFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFocusIdPrefix = "cache:focus:id:"
)

type (
	focusModel interface {
		Insert(ctx context.Context, data *Focus) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Focus, error)
		Update(ctx context.Context, data *Focus) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFocusModel struct {
		sqlc.CachedConn
		table string
	}

	Focus struct {
		Id   int64  `db:"id"`
		Name string `db:"name"`
	}
)

func newFocusModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFocusModel {
	return &defaultFocusModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`focus`",
	}
}

func (m *defaultFocusModel) Delete(ctx context.Context, id int64) error {
	focusIdKey := fmt.Sprintf("%s%v", cacheFocusIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, focusIdKey)
	return err
}

func (m *defaultFocusModel) FindOne(ctx context.Context, id int64) (*Focus, error) {
	focusIdKey := fmt.Sprintf("%s%v", cacheFocusIdPrefix, id)
	var resp Focus
	err := m.QueryRowCtx(ctx, &resp, focusIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", focusRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFocusModel) Insert(ctx context.Context, data *Focus) (sql.Result, error) {
	focusIdKey := fmt.Sprintf("%s%v", cacheFocusIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?)", m.table, focusRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name)
	}, focusIdKey)
	return ret, err
}

func (m *defaultFocusModel) Update(ctx context.Context, data *Focus) error {
	focusIdKey := fmt.Sprintf("%s%v", cacheFocusIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, focusRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Id)
	}, focusIdKey)
	return err
}

func (m *defaultFocusModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFocusIdPrefix, primary)
}

func (m *defaultFocusModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", focusRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFocusModel) tableName() string {
	return m.table
}


