// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	focus "go-zero/internal/handler/focus"
	"go-zero/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: HelloHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: focus.GetFocusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/addFocus",
				Handler: focus.AddFocusHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/deleteFocus",
				Handler: focus.DeleteFocusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/oneFocus",
				Handler: focus.GetFocusByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/updateFocus",
				Handler: focus.UpdateFocusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/focus"),
	)
}
