// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddFocusRequest struct {
	Name string `json:"name"`
}

type FocusRequest struct {
	Id int64 `json:"id"`
}

type FocusResp struct {
	Code int                    `json:"code"`
	Msg  string                 `json:"msg"`
	Data map[string]interface{} `json:"data,omitempty"`
}

type HelloReq struct {
	Name string `json:"name"`
}

type HelloResp struct {
	Message string `json:"message"`
}

type UpdateFocusRequest struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}


