services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - clickhouse-demo

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_container
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - clickhouse-demo
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

networks:
  clickhouse-demo:
    driver: bridge
