-- h2init.sql
CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS schedule (
    id INT AUTO_INCREMENT PRIMARY KEY,
    job VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO users (id, name) VALUES (1, 'admin');
INSERT INTO users (id, name) VALUES (2, 'user');

-- Create a new user and grant authorization
CREATE USER  IF NOT EXISTS testUser PASSWORD '123456';
GRANT SELECT, INSERT, UPDATE ON users TO testUser;

CREATE USER  IF NOT EXISTS sa PASSWORD '123456';
GRANT SELECT, INSERT, UPDATE ON users TO sa;
--ALTER USER sa SET PASSWORD 'meow'

