spring:
  application:
    name: playground
    
  datasource:
    url: jdbc:mysql://localhost:3306/testspringdata?TimeZone=Asia/Taipei
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  devtools:
    restart:
      enabled: true
      
logging:
  level:
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.transaction: TRACE
    org.springframework.transaction.interceptor: TRACE
    
country:
  mapping:
    taiwan: 台灣
    us: 每國
  
  