// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/holidays": {
            "get": {
                "description": "?πÊ??•Ê??åÁ??ãÊ?ÊßãÊü•Ë©¢Â???,
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holidays"
                ],
                "summary": "?•Ë©¢?áÊó•Ë≥áË?",
                "parameters": [
                    {
                        "type": "string",
                        "description": "?•Ë©¢?•Ê? (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "?üÈ?Ê©üÊ??çÁ®±",
                        "name": "operator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "?ãÂ??•Ê? (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ÁµêÊ??•Ê? (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "?µÂª∫?∞Á??áÊó•Ë®òÈ?",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holidays"
                ],
                "summary": "?µÂª∫?áÊó•",
                "parameters": [
                    {
                        "description": "?áÊó•Ë≥áË?",
                        "name": "holiday",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.HolidayOperator"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.HolidayOperator"
                        }
                    }
                }
            }
        },
        "/api/v1/holidays/{id}": {
            "put": {
                "description": "?¥Êñ∞?áÊó•Ë®òÈ?",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holidays"
                ],
                "summary": "?¥Êñ∞?áÊó•",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "?áÊó•ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "?áÊó•Ë≥áË?",
                        "name": "holiday",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.HolidayOperator"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.HolidayOperator"
                        }
                    }
                }
            },
            "delete": {
                "description": "ËªüÂà™?§Â??•Ë???,
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holidays"
                ],
                "summary": "?™Èô§?áÊó•",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "?áÊó•ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.HolidayOperator": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "string"
                },
                "operator": {
                    "type": "string"
                },
                "region_city": {
                    "type": "string"
                },
                "region_town": {
                    "type": "string"
                },
                "region_village": {
                    "type": "string"
                },
                "source": {
                    "description": "'weekend', 'disaster', 'google', 'custom'",
                    "type": "string"
                },
                "type": {
                    "description": "'holiday' or 'workday'",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
